import type {Metadata} from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "mp-donations",
  description: "Generated by appncy",
};

interface RootProps {
  children: React.ReactNode;
}

export default function RootLayout({children}: RootProps) {
  return (
    <html lang="en">
      <body className="dark">{children}</body>
    </html>
  );
}
